### PR TITLE
Basic exceptions exercise for try... catch logic

### PR DESCRIPTION
**Pull request by mikeymike**
User is required to create a program that outputs a specific string when a file does not exist. 

They are urged to use `SplFileObject` with `try... catch` logic for the `RuntimeException` it throws when the file path can't be opened. They are also banned from using `array_filter` and `file_exists` functions to prevent the approach detailed in the `ArrayWeGo` exercise. 

Also as we are trying to be an educational resource I thought it may be best to add a disclaimer to this exercise as using exceptions as a method of control flow seems to be frowned upon. Let me know your thoughts on this.

### CODE REVIEW

**Comment by mikeymike** [comment]
Thoughts on removing tests from Scrutinzer, they drop the code quality down :(

**Comment by AydinHassan** [comment]
@mikeymike Lets leave the tests and disable the duplication check. It's mostly bogus IMO. Make those small doc changes and we'll get this merged :+1:

**Comment by mikeymike** [comment]
@AydinHassan Updated, made some minor changes to the expected output to better fit the new documentation :smile:

**Comment by AydinHassan** [comment]
:ox:

**Pull request merged**
