### PR TITLE
HTTP JSON API exercise

### PR DESCRIPTION
**Pull request by AydinHassan**

### CODE REVIEW

**Comment by AydinHassan** [comment]
Yo @mikeymike, give this a blast when you get some time :)

**Comment by mikeymike** [comment]
Looks good man. Would prefer the tests to be more split but doesn't bother me that much.

Also according to codecov it's not covering the exercise o_0

**Comment by AydinHassan** [comment]
I mean actually check out the exercise and have a play, see what you think :)

**Comment by AydinHassan** [comment]
The code is definitely covered, codecov is being lame. I really don't see the point to split out the tests. I see different test methods as testing different permutations based on parameters or whatever. This is just a bunch of getters that do the same thing every time.

**Pull request merged**
