### PR TITLE
Fix dependency heaven solution

### PR DESCRIPTION
**Pull request by AydinHassan**
Request was never dispatched + `json_encode` does not call `__toString()`

### CODE REVIEW

**Comment by AydinHassan** [comment]
@mikeymike

**Comment by mikeymike** [comment]
Nice spot dude, can't believe I missed this. Do we need the test solutions to be updated too?

**Comment by AydinHassan** [comment]
@mikeymike Possibly, the tests have passed though? What am I missing?

**Comment by mikeymike** [comment]
Not missing anything, I just meant to keep it all consistent. Dw though it doesn't actually affect anything because it's just testing the composer section not the actual solution itself. 

Going to merge this now :+1:

**Pull request merged**
